### ISSUE TITLE
希望使用相对路径以便于部署在子目录下

### ISSUE THREAD

**Issue by Landius** [gnattu/bbdown-webui#1]
https://github.com/gnattu/bbdown-webui/blob/776b865250145cb7172f79d71c3cde218b1dca55/src/App.tsx#L44
用 `/userconfig.json` 的话挂在 `bili.local` 可以正常用，挂在 `bili.local/webgui`  下就不行了
而 `userconfig.json` 部署在这两个地址都可以用

（主要是不想弄太多域名🤣

**Comment by gnattu** [comment]
Done: https://github.com/gnattu/bbdown-webui/releases/tag/v0.1.3

**Comment by Landius** [comment]
> Done: https://github.com/gnattu/bbdown-webui/releases/tag/v0.1.3

```html
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon-bbdown.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="referrer" content="no-referrer" />
    <title>BBDown WebUI</title>
    <script type="module" crossorigin src="/assets/index-5e25695a.js"></script>
    <link rel="stylesheet" href="/assets/index-81dd19b2.css">
  </head>
```

刚刚看了下，还是不行，生成的 `index.html` 还是用的绝对路径。
似乎还要改下 `vite.config` 里的 `base` 值。

**Comment by gnattu** [comment]
试一下v0.1.4

**Comment by Landius** [comment]
> 试一下v0.1.4

可以了
