### ISSUE TITLE
是否支持从服务端本机发起http请求？

### ISSUE THREAD

**Issue by jindongjie** [gnattu/bbdown-webui#3]
我把该服务部署在我的服务器上，可是发起请求是客户端的127.0.0.1,请问能不能实现从服务端本机发起http请求？我拿了10tb的硬盘来下电影，开了一个月的大会员，立志把所有付费视频下下来：）

**Comment by gnattu** [comment]
无能为力，你只能在`userconfig.json`里把ip改成服务器的ip，或者有域名改成服务器的域名。因为这个客户端本质上是完全跑在你的浏览器里的，没有任何服务端成分
